### ISSUE TITLE
After I run the project, how can I get some data(statistics)?

### ISSUE THREAD

**Issue by zzz6519003** [msgport/ormponder#3]
<img width="613" alt="image" src="https://github.com/darwinia-network/ormponder/assets/1625608/b864423e-8b30-4953-8a00-106485dffba3">

**Comment by zzz6519003** [comment]
Can give an example GQL query? XD

**Comment by jiguantong** [comment]
For example
```
{
  MessageAccepted(id: "123") {
       msgHash,
       root
}
```
But currently, there's no data on Tron shasta, so it will return null.

**Comment by zzz6519003** [comment]
So how can I get some data to see see XD

**Comment by jiguantong** [comment]
![image](https://github.com/darwinia-network/ormponder/assets/27564714/83bf71c7-bb79-455f-9622-e2d65b385bbf)
https://ormponder-production.up.railway.app/
